services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb+srv://menuradulkith12:Qwe123@cluster0.ah3pppy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  client:
    build: ./Web-app/frontend
    container_name: client_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./Web-app/frontend:/app
